### PR TITLE
Jack client fixes

### PR DESCRIPTION
**Pull request by catfact**
several fixes for the jack/OSC client, with the main goal of making it easier / feasible to build and run on macOS.

### CODE REVIEW

**Comment by catfact** [comment]
oh also this pulls in the `rec_once` change.  i guess that should be propagated to norns if we can be triple-sure that it will not impose a performance problem (new crackles) on cm3. 

will have a performance / new features pass soon.

**Comment by tehn** [comment]
awesome, very happy to see this

**Comment by schollz** [comment]
@catfact I have a cm3 norns now and can do some rigorous performance testing. fwiw I use rec_once regularly in my script context (seemingly) without issues.

It's been awhile and I also will double check what you merged is up to date. I've been using this version for myself: https://github.com/schollz/softcut-lib/tree/rec-once5

**Comment by catfact** [comment]
@schollz i believe you that performance is fine. but i want to be sure.

there is another sense in which this change increases technical debt. there is a really specific mechanism for swapping per-sample update functions on each voice depdending on current play/rec flag status _at the top of each audio block_:

https://github.com/monome/softcut-lib/blob/main/softcut-lib/src/Voice.cpp#L60

if we are now _also_ adding conditionals that do similar behavior changes _per sample_, it doesn't make sense to keep this function-swapping mechanism: it's probably slightly detrimental to performance since we are now checking flags each frame anyways, but more importantly (to me) it is just nonsensical and a future reader of the code won't be able to determine its intent.

**Comment by catfact** [comment]
... it looks to me like you did consider this a bit more in further commits on your own fork.

**Comment by tehn** [comment]
my build is failing on ubuntu, and this error message is a bit inscrutable to me

```
[ 84%] Building CXX object clients/softcut_jack_osc/CMakeFiles/softcut_jack_osc.dir/src/BufDiskWorker.cpp.o
/home/tehn/local/softcut-lib/clients/softcut_jack_osc/src/BufDiskWorker.cpp:24:75: error: aggregate ‘std::array<softcut_jack_osc::BufDiskWorker::BufDesc, 16> softcut_jack_osc::BufDiskWorker::bufs’ has incomplete type and cannot be defined
   24 | std::array<BufDiskWorker::BufDesc, BufDiskWorker::maxBufs> BufDiskWorker::bufs;
      |                                                                           ^~~~
gmake[2]: *** [clients/softcut_jack_osc/CMakeFiles/softcut_jack_osc.dir/build.make:132: clients/softcut_jack_osc/CMakeFiles/softcut_jack_osc.dir/src/BufDiskWorker.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:142: clients/softcut_jack_osc/CMakeFiles/softcut_jack_osc.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

(boost is installed)

**Comment by catfact** [comment]
that's odd, i just tried a build on ubuntu with no issues.

are you using a very old version of ubuntu and/or gcc? this needs c++17 support, which means >= gcc 8. i'm on gcc 11 and recently upgraded ubuntu to 22.04.

**Comment by catfact** [comment]
(boost should not be needed now btw)

**Comment by tehn** [comment]
excellent re: no boost needed

```
gcc (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0
```

on ubuntu 23.04

---

will keep messing around with it

**Comment by catfact** [comment]
huh. how did you invoke cmake and what is the cmake version?

i did this

```
cd $SOFTCUT_LIB_DIR
mkdir build
cmake -S . -B build/ -DCMAKE_BUILD_TYPE=Release
cmake --build build/
```

cmake 3.22.1 (though i'd expect older versions to work fine)

**Comment by catfact** [comment]
oh maybe check `g++ --version` to verify its the same?

**Comment by tehn** [comment]
cmake version 3.25.1
g++ (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0

followed your precise build, same messages. clean clone.

**Comment by catfact** [comment]
tried with clean clone just to be sure, no issues.

honestly this feels like a toolchain bug. i wasn't planning on going up to ubuntu 23, too fresh. but guess i will now

**Comment by tehn** [comment]
let me try on another system (manjaro)

**Comment by tehn** [comment]
ok, since manjaro is arch, it's all edge versions. ran a system update (because this system doesn't get used a lot, and i needed cmake) so all versions are new

different error now:
```
In file included from /home/tehn/local/softcut-lib/clients/softcut_jack_osc/src/OscInterface.cpp:13:
/home/tehn/local/softcut-lib/clients/softcut_jack_osc/src/BufDiskWorker.h:37:25: error: field ‘path’ has incomplete type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’}
   37 |             std::string path;
      |                         ^~~~
In file included from /usr/include/c++/13.2.1/iosfwd:41,
                 from /usr/include/c++/13.2.1/bits/std_thread.h:38,
                 from /usr/include/c++/13.2.1/thread:45,
                 from /home/tehn/local/softcut-lib/clients/softcut_jack_osc/src/OscInterface.cpp:8:
/usr/include/c++/13.2.1/bits/stringfwd.h:72:11: note: declaration of ‘std::string’ {aka ‘class std::__cxx11::basic_string<char>’}
   72 |     class basic_string;
      |           ^~~~~~~~~~~~
make[2]: *** [clients/softcut_jack_osc/CMakeFiles/softcut_jack_osc.dir/build.make:118: clients/softcut_jack_osc/CMakeFiles/softcut_jack_osc.dir/src/OscInterface.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:142: clients/softcut_jack_osc/CMakeFiles/softcut_jack_osc.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by catfact** [comment]
i upgraded to 23.04. kind of regret breaking my rule (only LTS releases from canonical.) oh well, will work it out.

i am getting your first error now. both of these are pretty fucked up and nonsensical. i'll chase the first one. 

yeah, my first hypothesis was a super old gcc, but now of course its clear that it is new gcc that is messed up.

**Comment by catfact** [comment]
(like in both cases it seems stdlib is just not being linked.)

**Comment by catfact** [comment]
aha fuuck

> The following headers are used less widely in libstdc++ and may need to be included explicitly when compiled with GCC 12:

<memory> (for std::shared_ptr, std::unique_ptr etc.)
<iterator> (for std::istream_iterator, std::istreambuf_iterator)
<algorithm> (for std::for_each, std::copy etc.)
<utility> (for std::pair)
<array> (for std::array)
<atomic> (for std::atomic)

**Comment by catfact** [comment]
bleh i'm dumb. was just missing standard library includes. (in first case for sure, second looks like it too.) pushed and merged to main (and here, for good measure.) 
https://github.com/monome/softcut-lib/pull/70

(you didn't need to include these explicitly on older gcc; v12 is stricter. apparently as a byproduct of internal refactoring in the stdlib.)

@tehn this addresses the missing `array` for me on newbuntu. also added `<string>` where appropriate for the second issue. if you encounter other errors like this ("undefined" or "incomplete" types from the standard library), check for inclusion of relevant headers i guess.

**Comment by catfact** [comment]
for reference:

https://gcc.gnu.org/gcc-12/porting_to.html

<blockquote>
 Some C++ Standard Library headers have been changed to no longer include other headers that were being used internally by the library. As such, C++ programs that used standard library components without including the right headers will no longer compile.

The following headers are used less widely in libstdc++ and may need to be included explicitly when compiled with GCC 12:

<memory> (for std::shared_ptr, std::unique_ptr etc.)
<iterator> (for std::begin, std::end, std::size, std::istream_iterator, std::istreambuf_iterator)
<algorithm> (for std::for_each, std::copy etc.)
<utility> (for std::pair)
<array> (for std::array)
<atomic> (for std::atomic)
<ctime> (for std::time, std::mktime etc.)
<pthread.h> (for pthread_create, pthread_mutex_t etc.)

</blockquote>

(it doesn't list `string`, so idk if that is the actual cause of the 2nd problem, but it looks similar.)

**Comment by tehn** [comment]
now builds perfectly everywhere, thank you. and i apologize i couldn't figure out that error message. still haven't gotten into c++.

**Pull request merged**
